### ISSUE TITLE
Invalid State: pending

### ISSUE THREAD

**Issue by mobiusint** [dcoles/acme-linode-objectstorage#4]
Hi there,
Thanks so much for this. I tried it from macos today and i received the following error. Here is the majority of the output. (FYI: Ichanged my bucket name => BUCKETNAME)

DEBUG:urllib3.connectionpool:http://**BUCKETNAME**:80 "HEAD /.well-known/acme-challenge/BmcmGIl_MLJ9o7jVIdmxYxGcm8oXzXcOyj88tXC8svk HTTP/1.1" 200 0
DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/chall-v3/170804966672/mkpqwg HTTP/1.1" 200 187
DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/chall-v3/170804966672/mkpqwg HTTP/1.1" 200 187
DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/chall-v3/170804966672/mkpqwg HTTP/1.1" 200 665
DEBUG:urllib3.connectionpool:https://api.linode.com:443 "POST /v4/object-storage/buckets/us-east-1/BUCKETNAME/object-url HTTP/1.1" 200 261
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): us-east-1.linodeobjects.com:443
DEBUG:urllib3.connectionpool:https://us-east-1.linodeobjects.com:443 "DELETE /BUCKETNAME/.well-known/acme-challenge/BmcmGIl_MLJ9o7jVIdmxYxGcm8oXzXcOyj88tXC8svk?Signature=EqopKbznzq866NfT3RaWe2DDCLc%3D&Expires=1667223743&AWSAccessKeyId=UQ9A5VC5FI7QSRZIJZPT HTTP/1.1" 204 0
INFO:root:Finalizing order
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/homebrew/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/josh/acme-linode-objectstorage/acme_linode_objectstorage/__main__.py", line 186, in <module>
    sys.exit(main())
  File "/Users/josh/acme-linode-objectstorage/acme_linode_objectstorage/__main__.py", line 150, in main
    order.finalize(csr)
  File "/Users/josh/acme-linode-objectstorage/acme_linode_objectstorage/acme.py", line 154, in finalize
    raise RuntimeError(f'Invalid state: {self.status}')
**_RuntimeError: Invalid state: pending_**

**Comment by mobiusint** [comment]
Hi again,
So I figured I would give it a shot & thanks again for the script!!! I had to remove the current "live" cert that was expiring and then run the script & it ran perfectly!!! Thank you again so much.

Cheers!

**Comment by dcoles** [comment]
Hi @mobiusint,

Thanks for the bug report! You're actually correct - there was a race condition where we didn't wait for an order to exit 'pending' before finalizing an order. This should now be fixed in 624ad6575b19a25c68c9158b613dd334c9439f88.

Glad the script is useful!

**Comment by mobiusint** [comment]
Hi **@dcoles** 
Awesome! I just tried it out & it works flawlessly with the updated code. Thank you so much!
