### ISSUE TITLE
ERROR: Challenge unsuccessful: pending

### ISSUE THREAD

**Issue by seandroms** [dcoles/acme-linode-objectstorage#8]
In the challenge response, I got the status "pending". So I had to change line 135 of `__main__.py` from:
```
challenge.poll_until_not({'processing'})
```
to:
```
challenge.poll_until_not({'pending','processing'})
```

**Comment by dcoles** [comment]
Hi @seandroms,

Thanks for the bug report! I hadn't seen this issue in the past, but I suspect this is what happens if the request gets queued on the Let's Encrypt side. Your fix looks like the right one so I'll apply right away.
