### ISSUE TITLE
Always failed

### ISSUE THREAD

**Issue by sleepfinance** [dcoles/acme-linode-objectstorage#9]
I always get this error> have tried all the steps I could. where Im I going wrong?
```
root@localhost:~# export LINODE_TOKEN=6b....(hidden for obvious reasons)
python3 -m acme_linode_objectstorage -k account_key.pem static.giveaways.finance
```
**Response**

```
INFO:root:Generating 2048-bit RSA private key
INFO:root:Creating CSR for static.giveaways.finance
ERROR: No matching bucket found
root@localhost:~#
```
I created a bucket with cname as name.  `static.giveaways.finance`
created cname pointing to my bucket url with same name  static.giveaways.finance

All works fine
**visiting subdomain**
<img width="798" alt="Screenshot 2024-06-16 at 8 10 57 PM" src="https://github.com/dcoles/acme-linode-objectstorage/assets/122859883/dbc2cced-a5ad-4e82-9f1b-deaeb4c1d0b2">
**Visting Domain**
<img width="749" alt="Screenshot 2024-06-16 at 8 11 24 PM" src="https://github.com/dcoles/acme-linode-objectstorage/assets/122859883/29e3b640-a1c1-4c2b-aea0-322ce344a500">

By this stage I expect it all to work when creating certficate> My API TOKEN has all access enabled

<img width="464" alt="Screenshot 2024-06-16 at 8 14 34 PM" src="https://github.com/dcoles/acme-linode-objectstorage/assets/122859883/43cc7d82-e1e1-4133-a8ca-e1ecab1b8607">

**Comment by dcoles** [comment]
Hi @sleepfinance,

By default the tool defaults to Linode's `us-east-1` cluster, but you're appear to be using a bucket in `eu-central-1`.

Would you please try again, with the `-C`/`--cluster` flag set to `eu-central-1`?

```bash
python3 -m acme_linode_objectstorage -k account_key.pem -c eu-central-1 static.giveaways.finance
```

**Comment by dcoles** [comment]
As of b36ab2852e72593f074a43c101ded19615eda660 the script now sets up the challenge in all buckets with a matching label. As such, the `--cluster` flag is no longer required.

It would be appreciated if you could try this version out to ensure that it's fixed for non-`us-east-1` clusters.
